[2020-09-25 17:51:53 +0800] [21897] [INFO] Starting gunicorn 20.0.4
[2020-09-25 17:51:53 +0800] [21897] [INFO] Listening at: http://9.135.94.3:8080 (21897)
[2020-09-25 17:51:53 +0800] [21897] [INFO] Using worker: gevent
[2020-09-25 17:51:53 +0800] [21900] [INFO] Booting worker with pid: 21900
[2020-09-25 17:51:53 +0800] [21901] [INFO] Booting worker with pid: 21901
[2020-09-25 17:51:53 +0800] [21902] [INFO] Booting worker with pid: 21902
[2020-09-25 17:51:53 +0800] [21903] [INFO] Booting worker with pid: 21903
[2020-09-25 17:51:53 +0800] [21901] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wsgi'
[2020-09-25 17:51:53 +0800] [21900] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wsgi'
[2020-09-25 17:51:53 +0800] [21902] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wsgi'
[2020-09-25 17:51:53 +0800] [21901] [INFO] Worker exiting (pid: 21901)
[2020-09-25 17:51:53 +0800] [21900] [INFO] Worker exiting (pid: 21900)
[2020-09-25 17:51:53 +0800] [21902] [INFO] Worker exiting (pid: 21902)
[2020-09-25 17:51:53 +0800] [21904] [INFO] Booting worker with pid: 21904
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 202, in run
    self.manage_workers()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 545, in manage_workers
    self.spawn_workers()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 617, in spawn_workers
    time.sleep(0.1 * random.random())
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 228, in run
    super().run()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 229, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
[2020-09-25 17:51:53 +0800] [21903] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wsgi'
[2020-09-25 17:51:53 +0800] [21903] [INFO] Worker exiting (pid: 21903)
[2020-09-25 17:51:53 +0800] [21904] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wsgi'
[2020-09-25 17:51:53 +0800] [21904] [INFO] Worker exiting (pid: 21904)
[2020-09-25 17:52:01 +0800] [22023] [INFO] Starting gunicorn 20.0.4
[2020-09-25 17:52:01 +0800] [22023] [INFO] Listening at: http://9.135.94.3:8080 (22023)
[2020-09-25 17:52:01 +0800] [22023] [INFO] Using worker: gevent
[2020-09-25 17:52:01 +0800] [22026] [INFO] Booting worker with pid: 22026
[2020-09-25 17:52:01 +0800] [22027] [INFO] Booting worker with pid: 22027
[2020-09-25 17:52:01 +0800] [22028] [INFO] Booting worker with pid: 22028
[2020-09-25 17:52:02 +0800] [22032] [INFO] Booting worker with pid: 22032
[2020-09-25 17:52:02 +0800] [22033] [INFO] Booting worker with pid: 22033
[2020-09-25 17:52:02 +0800] [22034] [INFO] Booting worker with pid: 22034
[2020-09-25 17:52:02 +0800] [22035] [INFO] Booting worker with pid: 22035
[2020-09-25 17:52:02 +0800] [22038] [INFO] Booting worker with pid: 22038
[2020-09-25 17:52:02 +0800] [22041] [INFO] Booting worker with pid: 22041
[2020-09-25 17:52:02 +0800] [22043] [INFO] Booting worker with pid: 22043
[2020-09-25 17:52:02 +0800] [22045] [INFO] Booting worker with pid: 22045
[2020-09-25 17:52:02 +0800] [22047] [INFO] Booting worker with pid: 22047
[2020-09-25 17:52:02 +0800] [22050] [INFO] Booting worker with pid: 22050
[2020-09-25 17:52:02 +0800] [22051] [INFO] Booting worker with pid: 22051
[2020-09-25 17:52:02 +0800] [22052] [INFO] Booting worker with pid: 22052
[2020-09-25 17:52:02 +0800] [22054] [INFO] Booting worker with pid: 22054
[2020-10-13 10:17:18 +0800] [28316] [INFO] Booting worker with pid: 28316
[2020-10-13 10:17:18 +0800] [28320] [INFO] Booting worker with pid: 28320
[2020-10-13 10:17:18 +0800] [28329] [INFO] Booting worker with pid: 28329
[2020-10-13 10:17:18 +0800] [28336] [INFO] Booting worker with pid: 28336
[2020-10-13 10:17:19 +0800] [28340] [INFO] Booting worker with pid: 28340
[2020-10-13 10:17:19 +0800] [28344] [INFO] Booting worker with pid: 28344
[2020-10-13 10:17:19 +0800] [22023] [INFO] Handling signal: hup
[2020-10-13 10:17:19 +0800] [22023] [INFO] Hang up: Master
[2020-10-13 10:17:19 +0800] [28345] [INFO] Booting worker with pid: 28345
[2020-10-13 10:17:19 +0800] [28346] [INFO] Booting worker with pid: 28346
[2020-10-13 10:17:19 +0800] [28348] [INFO] Booting worker with pid: 28348
[2020-10-13 10:17:19 +0800] [28349] [INFO] Booting worker with pid: 28349
[2020-10-13 10:17:19 +0800] [28354] [INFO] Booting worker with pid: 28354
[2020-10-13 10:17:19 +0800] [22023] [INFO] Handling signal: term
[2020-10-13 10:17:19 +0800] [28356] [INFO] Booting worker with pid: 28356
[2020-10-13 10:17:19 +0800] [28353] [INFO] Booting worker with pid: 28353
[2020-10-13 10:17:19 +0800] [28347] [INFO] Booting worker with pid: 28347
[2020-10-13 10:17:19 +0800] [28350] [INFO] Booting worker with pid: 28350
[2020-10-13 10:17:19 +0800] [28351] [INFO] Booting worker with pid: 28351
[2020-10-13 10:17:19 +0800] [28355] [INFO] Booting worker with pid: 28355
[2020-10-13 10:17:19 +0800] [28359] [INFO] Booting worker with pid: 28359
[2020-10-13 10:17:19 +0800] [28358] [INFO] Booting worker with pid: 28358
[2020-10-13 10:17:19 +0800] [28352] [INFO] Booting worker with pid: 28352
[2020-10-13 10:17:19 +0800] [28357] [INFO] Booting worker with pid: 28357
[2020-10-13 10:17:19 +0800] [28360] [INFO] Booting worker with pid: 28360
[2020-10-13 02:17:19 +0000] [28329] [INFO] Worker exiting (pid: 28329)
[2020-10-13 02:17:19 +0000] [28336] [INFO] Worker exiting (pid: 28336)
[2020-10-13 02:17:19 +0000] [28340] [INFO] Worker exiting (pid: 28340)
[2020-10-13 02:17:20 +0000] [28316] [INFO] Worker exiting (pid: 28316)
[2020-10-13 02:17:20 +0000] [28320] [INFO] Worker exiting (pid: 28320)
